Theoretical Questions:
1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations? **bold text**

ANS - NumPy provides efficient data structures for numerical operations, especially arrays and matrices. It enhances Python’s capabilities by enabling faster computations, vectorized operations, and memory-efficient data storage, which are essential for scientific computing and data analysis.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other? **bold text**

ANS- np.mean() calculates the arithmetic mean of the array, while np.average() can compute a weighted average if weights are provided. Use np.average() when you want to account for weights, otherwise, np.mean() suffices.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays. **bold text**

ANS- 1D: arr[::-1] reverses a 1D array.
2D: arr[::-1, ::-1] reverses rows and columns along both axes.

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

ANS-Use arr.dtype to determine the data type. Data types are crucial for memory management and performance, as they define how much memory each element consumes and how operations are performed.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ANS-ndarrays are multi-dimensional, homogeneous arrays with fast element access and mathematical operations. Unlike Python lists, ndarrays are optimized for numerical tasks and support vectorized operations.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ANS-NumPy arrays are faster and more memory-efficient than Python lists due to contiguous memory allocation, vectorized operations, and lower overhead for numerical computations.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

ANS-
vstack(): Stacks arrays vertically (row-wise).
hstack(): Stacks arrays horizontally (column-wise).
Example:
np.vstack([arr1, arr2])  # vertical stacking
np.hstack([arr1, arr2])  # horizontal stacking


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

ANS-
fliplr(): Flips the array left to right (columns reversed).
flipud(): Flips the array upside down (rows reversed)

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ANS-Splits an array into sub-arrays. If the split is uneven, some sub-arrays will have more elements than others. For example, np.array_split(arr, 3) divides an array into three parts, with the remainder handled as needed.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

ANS-
Vectorization: Replaces explicit loops with optimized array operations for faster execution.
Broadcasting: Allows operations on arrays of different shapes by automatically expanding their dimensions. Both improve efficiency by avoiding loops.

Practical Questions:
1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
a= np.random.randint(1,100,(3,3))
a.T

array([[ 1, 12, 76],
       [57, 54, 13],
       [61, 95, 58]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a.reshape(2,5)
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
a= np.random.rand(4,4)
a
np.pad(a,pad_width=1,mode='constant',constant_values=0)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.23735004, 0.76546124, 0.99097989, 0.8792744 ,
        0.        ],
       [0.        , 0.51947537, 0.25865435, 0.0060043 , 0.20873101,
        0.        ],
       [0.        , 0.21874839, 0.89557273, 0.29945507, 0.58833539,
        0.        ],
       [0.        , 0.94333843, 0.64507293, 0.95758315, 0.73106001,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
a= np.random.randint(10,60,5)
a

array([34, 54, 57, 18, 57])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
a=np.array(['python','numpy','pandas'])
a
a[0].upper()
a[0].lower()
a[0].title()
a[1].upper()
a[1].lower()
a[1].title()
a[2].upper()
a[2].lower()
a[2].title()

'Pandas'

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
words = np.array(['apple', 'banana', 'cherry'])
words_with_spaces = np.array([' '.join(word) for word in words])

print(words_with_spaces)



['a p p l e' 'b a n a n a' 'c h e r r y']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 =np.array([[6,2,73],[4,45,6],[7,82,9]])
arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2

array([[0.16666667, 1.        , 0.04109589],
       [1.        , 0.11111111, 1.        ],
       [1.        , 0.09756098, 1.        ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
a=np.eye(5)
np.diag(a)

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [ ]:
a = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

primes = np.array([num for num in a if is_prime(num)])
print("Prime Numbers:\n", primes)

Prime Numbers:
 [397 967 157 331 811 191 613 983 197 947 283 389 179 677 617  43 601]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages

In [ ]:
temperatures = np.random.uniform(low=-10, high=35, size=30)
temperatures_reshape = temperatures.reshape(5,6)
weekly_averages = np.mean(temperatures_reshape, axis=1)
weekly_averages

array([21.21861767,  8.9307787 , 12.31664027, 17.33221257, 13.09146786])